spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

nympheas:
  base-url: ${APP_BASE_URL}